version: "3.8"

services:
  backend:
    image: be-prod
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    depends_on:
      - redis
      - mongo
    container_name: be-prod
    environment:
      - REDIS_HOST=redis
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database

  frontend:
    image: fe-prod
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80
    depends_on:
      - backend
    container_name: fe-prod
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3001

  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    container_name: mongodb
